-- phpMyAdmin SQL Dump
-- version 4.9.2
-- https://www.phpmyadmin.net/
--
-- Máy chủ: 127.0.0.1:3306
-- Thời gian đã tạo: Th12 11, 2020 lúc 06:18 AM
-- Phiên bản máy phục vụ: 10.4.10-MariaDB
-- Phiên bản PHP: 7.3.12

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Cơ sở dữ liệu: `tkweb`
--

-- --------------------------------------------------------

--
-- Cấu trúc bảng cho bảng `sanpham`
--

DROP TABLE IF EXISTS `sanpham`;
CREATE TABLE IF NOT EXISTS `sanpham` (
  `ma` int(11) NOT NULL AUTO_INCREMENT,
  `ten` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `mota` text COLLATE utf8_unicode_ci DEFAULT NULL,
  `hinh` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `trangthai` int(11) DEFAULT NULL,
  `gia` int(11) DEFAULT NULL,
  PRIMARY KEY (`ma`)
) ENGINE=MyISAM AUTO_INCREMENT=33 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

--
-- Đang đổ dữ liệu cho bảng `sanpham`
--

INSERT INTO `sanpham` (`ma`, `ten`, `mota`, `hinh`, `trangthai`, `gia`) VALUES
(1, 'MultiVitamin Biotech\r\n', 'Multivitamin for Women - 60 Tablets - Biotech USA - Woman\r\n\r\nMultivitamin for women from Biotech USA is a natural nutritional supplement, of high quality, for active women who wish to maintain in optimal conditions their health and athletic state.\r\n\r\nThe formula contains plant extracts that provide 12 vitamins, 9 essential minerals and the best nutritional complexes for women\'s diet, as well as lycopene, lutein and alpha lipoic acid.\r\n\r\nMultivitamin for women from Biotech USA has a potent antioxidant and nutritional effect, which supports bone health and improves the vital functions of the female organism. Ideal to increase energy and avoid the symptoms of exhaustion that prevent an active rhythm of life.\r\n\r\nMultivitamin for women Biotech USA is the nutritional supplement for women of higher quality that gives greater benefits to women\'s health.\r\n\r\nThis formula provides the greatest effectiveness in improving defenses, increasing energy, shaping the figure and maintaining the ideal weight. Ideal for women athletes or for active women who require more defenses, more energy and vitality to maintain a very dynamic rhythm of life.\r\n\r\nContainer Size: 60 tablets\r\n\r\nServing Size: 2 tablets\r\n\r\nServings Per Container: 30\r\n\r\n Amount Per Serving:', 'img/Multi.png', 1, 450000),
(2, 'One A Day Women', 'One A Day Women\'s is a complete multivitamin designed specifically for leading health concerns of women. After all, bone strength isn\'t an issue just for older women. You can actually start to lose bone mass as early as your 30s. That\'s why One A Day Women\'s contains a high level of Calcium to support strong bones and more Vitamin D than Centrum Women Under 50 to support strong bones and aid calcium absorption. One A Day Women\'s is specially formulated to support.Bone Strength with a high level of Calcium, more Vitamin D and MagnesiumHeart Health with Vitamins B6, B12, C, E and Folic AcidImmunity with Vitamins C, A, E and SeleniumPhysician Energy with B vitamins and Chromium to help convert food to fuelHealthy Reproductive System with Folic Acid, Magnesium, Zinc and Calcium. Provides nutritional support during PMS and MenopauseHealthy Skin with Vitamins A, C, Copper and Iron', 'img/Multi1.jpeg', 1, 540000),
(3, 'Multivitamin Applied', 'Multi-Vitamin Complex contributes to the normal function of the immune system during and after intense physical exercise, the nervous system as well as normal muscle and cognitive function and the normal formation of connective tissue.\r\n\r\nKEY BENEFITS\r\n\r\n30+ Vitamins, Minerals, Probiotics & Antioxidants\r\n\r\nOnly the Most Bioavailable Sources Used\r\n\r\nLeading Dosages of Every Ingredient\r\n\r\nHalal Certified Product\r\n\r\nSERVING AMOUNT / SUGGESTED USE\r\n\r\nTake 1 tablet, 3 times daily with food.\r\n\r\nServing size: 1 Tablets\r\n\r\nServing per container: 90', 'img/Multi2.png', 1, 350000),
(4, 'MultiVitamin Biotech', 'Multivitamin for Men - 60 Tablets - Biotech USA - \r\n\r\nMultivitamin for Men from BiotechUSA is a supplement specially developed to provide the nutrients required by the male body.\r\n\r\nThis formula contains a unique blend of antioxidants, amino acid complexes, and fruit and vegetable extracts that promote good health and long-term performance improvement.\r\n\r\nSpecifically formulated for maximum nutrition efficiency for men, with 12 types of vitamins, 10 types of minerals, 14 types of antioxidants and 5 types of amino acids. It is a multivitamin and multimineral complete with recommended amounts of nutrients for sportsmen with high physical demands, or people who do not play sports but need to balance a poor diet.\r\n\r\nMultivitamin for Men from BiotechUSA is the ideal supplement for men who play sports and want to maintain optimal health and performance, as well as sedentary men who need to improve their physical condition.\r\n\r\nThis is a high quality product formulated by BiotechUSA, one of the most reputed companies in the world for the high level of effectiveness of its supplements for athletes.\r\n\r\nRecommended Use: 2 tablets daily, with meals', 'img/Multi3.jpg', 1, 450000),
(5, 'Complete Multivitamin', 'Complete Multi Vitamin Complex cung cấp đầy đủ hơn 30 loại vitamin và khoáng chất, cùng với chiết xuất từ ​​trái cây và thực vật. Không những thế, nó còn bổ sung thêm Lactobacillus Acidophilus, Inositol và chiết xuất hạt tiêu đen.\r\n\r\nKhông giống như hầu hết các chất bổ sung vitamin tổng hợp khác, Complete MultiVitamin Complex là công thức cao cấp sử dụng lượng vitamin và khoáng chất dồi dào, đặc biệt để đáp ứng nhu cầu hàng ngày của các vận động viên và người tập thể dục thao. Các thành phần trong Complex MultiVitamin Complex góp phần vào việc chuyển hóa năng lượng bình thường, hỗ trợ chức năng của hệ thống miễn dịch và tổng hợp axit amin bình thường, cùng vô số lợi ích khác.', 'img/Multi4.jpg', 1, 650000),
(6, 'MuscleTech Platinum', 'Platinum Vitamin 90 Viên thuộc một trong những sản phẩm vitamin cung cấp nguồn dưỡng chất thiết yếu cho cơ thể. Sản phẩm này có vai trò quan trọng trong việc đảm bảo cho cơ thể khả năng chịu đựng tốt trong những lúc cần phải luyện tập trong thời gian dài.\r\n\r\nPlatinum Vitamin 90 Viên được sản xuất bởi hãng Muscletech, đây là nhãn hiệu nổi tiếng về cung cấp những sản phẩm bổ sung chất dinh dưỡng cần thiết trong khi luyện tập. Và cũng là một trong số các hãng nhận được nhiều sự tin tưởng từ cộng động Gymer.\r\n\r\nPlatinum Vitamin 90 Viên thuộc một trong những sản phẩm vitamin cung cấp nguồn dưỡng chất thiết yếu cho cơ thể. Sản phẩm này có vai trò quan trọng trong việc đảm bảo cho cơ thể khả năng chịu đựng tốt trong những lúc cần phải luyện tập trong thời gian dài.\r\n\r\nPlatinum Vitamin 90 Viên được sản xuất bởi hãng Muscletech, đây là nhãn hiệu nổi tiếng về cung cấp những sản phẩm bổ sung chất dinh dưỡng cần thiết trong khi luyện tập. Và cũng là một trong số các hãng nhận được nhiều sự tin tưởng từ cộng động Gymer.\r\n\r\n', 'img/Multi5.jpg', 1, 475000),
(7, 'Daily Multivitamin', 'Daily Multivitamin là một phương án tuyệt vời nhằm đạt được chuẩn lượng vitamin cần thiết cho cơ thể (RDA). Daily Multivitamin chưa 7 loại vitamin cần thiết, bao gồm vitamin B , vitamin C, E, A và D3,\r\nDaily Vitamin - Multi Vitamin , cung cấp tất cả những loại vitamin và khoáng chất cho cơ thể chỉ trong 1 viên, giúp duy trì sự sống cũng như nâng cao sức khỏe cho việc tập luyện.', 'img/Multi6.jpg', 1, 310000),
(8, 'Mutant MultiVitamin', 'MUTANT CAFFEINE khan được xây dựng để trở thành công thức hoàn hảo sức mạnh và gia năng lượng xúc tác! Đó là khả năng siêu sức mạnh cho cơ thể của bạn cho các bài tập mạnh mẽ hiện nay, chưa từng có. CAFFEINE nhanh chóng cung cấp các cấu trúc phân tử đúng với các hệ thống năng lượng của bạn tăng cường năng lượng . * CAFFEINE cũng có thể hỗ trợ tăng sự tỉnh táo và thần kinh cung cấp cho bạn sự gia tăng để tối ưu hóa các buổi huấn luyện vất vả khó khăn của bạn *. Không chỉ là một chất kích thích, hợp chất mạnh mẽ này đạt sâu vào các tế bào cơ để cung cấp kéo dài độ bền và trì hoãn sự khởi đầu của sự mệt mỏi cơ bắp bằng tập luyện nhiều hơn.', 'img/Multi7.jpg', 1, 500000),
(17, 'Bulk Powder', 'Pure Whey Protein ™ cung cấp dinh dưỡng cao! Đây là một chất bột whey chất lượng cao, sản xuất trực tiếp từ sữa bò Châu Âu, sử dụng sữa bò ăn cỏ, và chứa 82% Whey Protein. Bột protein này đã được xử lý cho dễ dàng pha và có sẵn trong 23 hương vị ngon thơm ngon. Thành phần protein cao, ít chất béo và carbohydrate thấp của Pure Whey Protein ™ làm cho nó trở thành sự lựa chọn lý tưởng cho bất cứ ai tìm kiếm để bổ sung cho lối sống lành mạnh hiện tại của họ. Protein cũng làm tăng cảm giác sung mãn, để bạn cảm thấy đầy đủ hơn nữa\r\n\r\nVới thành phần axit amin tuyệt vời, bao gồm các axit amin nhánh chi tiết, Pure Whey Protein ™ lý tưởng cho bất cứ ai muốn bổ sung protein vào chế độ ăn uống của họ, là một phần của lối sống cân bằng lành mạnh. Pure Whey Protein ™ cũng có thể được sử dụng để tạo cơ, vì protein đóng góp cho sự phát triển của khối cơ. Ngoài ra, Pure Whey Protein ™ còn ít carbohydrate, chất béo, lactose và cholesterol, làm cho nó trở thành một lựa chọn lành mạnh cho việc cung cấp protein chất lượng cao.', 'img/whey.jpg', 1, 1500000),
(18, 'Rule 1', 'Rule One Protein không tiếc chi phí khi xây dựng công thức của R1 Protein ™, chỉ tìm nguồn cung ứng tốt nhất, nguyên liệu tinh khiết nhất để dần trở thành một loại đạm whey tốt nhất. Tất cả các protein của chúng tôi đang thực sự instantized (đầy đủ kết tụ) để đảm bảo dễ dàng trộn, ngay cả trong điều kiện giá lạnh nhất của chất lỏng. Plus, hương vị của chúng tôi là phun khô, có hương sâu sắc hơn, hương vị phong phú hơn sẽ không tiêu tan, ngay cả với thời hạn sử dụng kéo dài.\r\n\r\nCông thức hầu như không có chất béo, tinh bột, hoặc cholesterol - và ZERO bột kem thêm hoặc gums được thêm vào giốngcác sản phẩm protein khác có xu hướng sử dụng như chất tạo đặc - bạn đang nhận được một trong những sản phẩm cao cấp được phân lập tinh khiết nhất trên thị trường. Hãy nhớ rằng, các đầu vào tốt nhất = đầu ra tốt nhất.', 'img/whey1.png', 1, 1800000),
(19, 'Iso Surge', 'Bạn có muốn tiếp tục cuộc sống của mình với những hương vị quen thuộc hàng ngày? Hãy tìm cho mình một cảm giác mới lạ. MUTANT nghĩ rằng bạn đã quá chán để tiêu tiền vào những vị chocolate mà mọi người đều uống, hay vanilla thông thường đã quá quen thuộc.\r\n\r\nNếu bạn đã và đang trên con đường tìm kiếm sự mới lạ trong hương vị,chắc hẳn bạn mong muốn được thưởng thức GOURMET. Đó là lí do vì sao MUTANT luôn luôn đưa ra những hương vị độc đáo nhằm đáp ứng nhu cầu một phần khách hàng với  những yêu càu đặc biệt. Bao gồm cả  hương vị bánh kem tươi, gấp ba chocolate, Chocolate chip và bánh sinh nhật.\r\n\r\nMọi người đều biết MUTANT là chuyên gia hàng đầu về hương vị. Chúng tôi sử dụng hương vị để khiến sản phẩm của mình khác biệt và nổi trội. Đó là lí do tất cả những kiến thức về khẩu vị, thị hiếu khách hàng đều được vận dụng triệt để nhằm mang đến một trong các loại Hydrolyzed Whey tốt nhất trên thị trường. Đó chính là Mutant Iso Surge.\r\n\r\nIso Surge cung cấp thành phần whey gồm: Protein Isolate & Hydrolysate. Phòng thí nghiệm MUTANT sau thời gian dài nghiên cứu đã tạo ra sự đột biến của Protein và đột biến hương vị, đó là ISO SURGE có hai ưu điểm: tinh khiết và đơn giản.\r\n\r\nLưu ý: Sản phẩm này  được sử dụng như một thực phẩm bổ sung cho các chế độ ăn, tuyệt đối không thay thế sản phẩm như một chế độ ăn chính. Một bữa ăn tiêu chuẩn và cân bằng rất quan trọng cho sức khỏe người sử dụng. Cân nhắc trước khi mua bởi có những sản phẩm làm giả làm nhái trên thị trường, hãy chắc chắn rằng bạn chọn đúng nhà phân phối. Để xa tầm với trẻ em. Bảo quản nơi khô ráo thoáng mát.', 'img/whey2.png', 1, 1700000),
(20, 'BioTech Whey', 'Sữa Tăng Cơ Iso Whey Zero là một loại protein whey đơn thuần tinh khiết hấp thu cực nhanh và dễ dàng. Không chứa gluten, lactose, chất béo chuyển vị hoặc thêm đường.\r\n\r\nHàm lượng protien 88% trong mỗi serving và hàm lượng carbohydrate thấp.  Các axit amin bổ sung đóng góp vào phục hồi nhanh hơn và giảm đau cơ bắp. Nếu bạn dùng Iso Whey Zero BiotechUSA  thường xuyên và phát triển cơ bắp tối ưu nhất. ', 'img/whey3.jpg', 1, 1900000),
(21, 'Dymatize Iso', 'Mục tiêu của bạn là có một cơ thể săn chắc khỏe mạnh với những múi cơ mang lại vẻ tự tin cho bạn mỗi khi bạn cởi áo khoe body. Nhưng lại cảm thấy khó khăn trong việc bổ sung đủ nguồn Protein để xây dựng cơ bắp và hoàn thiện cơ thể \r\n\r\n \r\n\r\nVậy còn do dự gì nữa ISO 100 chắc chắn là một sự lựa chọn hoàn hảo giành cho bạn, không chỉ có vậy ISO 100 sẽ giúp bạn cải thiện và rút ngắn thời gian để bạn đạt được kết quả một cách sớm nhất bởi nguồn Protein tinh khiết mà ISO 100 mang lại cho bạn\r\n\r\n \r\n\r\nSản phẩm ISO 100 với nguồn Protein hấp thụ siêu nhanh của hãng Dymatize được rất nhiều vận động viện tin tưởng, chọn lựa và sử dụng. Đơn giản vì ISO 100 có tất cả những thứ bạn cần  với mục đích đẩy nhanh quá trình phục hồi, táo tạo các mô cơ đồng thời liên tục đẩy mạnh sản sinh tổng hợp Protein lên các mô cơ mới. ', 'img/whey4.jpg', 1, 1750000),
(22, 'Iso-Pro VX', 'Iso Pro gây ấn tượng với người dùng đó chính là 27g Protein mà sản phẩm này phục vụ trong mỗi khẩu phần. Đây là một tỷ lệ rất cao so với các dòng sản phẩm tương đương chỉ ở mức 25g hoặc thấp hơn. Có thể nói hàm lượng Protein cũng là một yếu tố để một người tiêu dùng lựa chọn sản phẩm này hoặc bỏ qua sản phẩm kia.', 'img/whey5.jpg', 1, 1950000),
(23, 'BPI Iso', 'Iso HD là một trong hàng trăm sản phẩm cung cấp protein cao cấp cho người tập luyện, thế nhưng sản phẩm này vẫn được ưa chuộng và trở thành một trong số sản phẩm Whey Protein có mức tiêu thụ rất cao. Vậy đặc điểm nào của Iso HD hấp dẫn người dùng?\r\n\r\n100% whey isolate protein\r\nTối ưu hóa khả năng hấp thụ\r\nTăng cường đẩy nhanh quá trình phát triển, đồng hóa cơ bắp\r\nĐẩy mạnh quá trình tái tạo các mô cơ', 'img/Whey6.jpg', 1, 1850000),
(24, 'Myprotein', 'Impact Whey Protein is a fast absorbing source of protein that is in fact a by-product formed during the manufacturing of milk and cheese. Impact Whey Protein contains over 80% of top quality, undenatured protein, providing a range of both essential and non-essential amino acids which are important for recovery and stimulating muscle growth. Impact Whey Protein is also low in fat and carbohydrates (lactose) which makes it a perfect source of whey protein for those looking to reduce body fat levels but increase lean mass. Impact Whey Protein is also available in over 25 delicious flavours which have been carefully taste tested to provide the best tasting whey available.*\r\n\r\nUp to 80% protein content\r\nHelps with the recovery and growth of lean muscle mass\r\n100% whey protein concentrate\r\nAmazing range of flavors and easy mixing\r\nGrade A ranking on LabDoor', 'img/whey7.jpg', 1, 1500000),
(9, 'Nasa Behava', '• PURE HIGH POTENCY 10MG DAILY DOSE - Every capsule delivers 10mg of Max Strength Astaxanthin.\r\n• staxanthin -180 Capsules- 6 MONTH SUPPLY – Each bottle contains 180 Capsules of Astaxanthin for a full 6 Month Supply. Most others offer 120 pills or less at a higher price point.\r\n• USING Astaxanthin Supplements is a great start to a healthier lifestyle\r\n• WE OFFER BEST VALUE ON AMAZON This package delivers 180 capsules of extra strength for all supported by 100% MONEY BACK GUARANTEE for products delivered within 30 days. Other companies may offer way less capsules or softgels, with less mg.\r\n• 100% Satisfaction Guarantee – If within 30 days your unhappy with your product in any way just send it back to us and we will fully refund your purchase price. No questions asked. ORDER RISK FREE', 'img/Astaxathin1.jpg', 1, 480000),
(10, 'Now Astaxathin', 'Astaxanthin là một carotenoids, được biết đến là các sắc tố có màu đỏ thẫm và được tìm thấy trong các loài sinh vật biển, đặc biệt như tảo, cá hồi, tôm càng, tôm hùm và trứng cá,v..v Tuy nhiên, các loài động vật không thể tự tổng hợp được hoạt chất này, mà cần được bổ sung thông qua chế độ ăn.\r\n\r\n \r\n\r\nLoài vi tảo lục Haematococcus Pluvialis được các nhà khoa học khẳng định có khả năng tự tổng hợp được Astaxanthin và hàm lượng hoạt chất trong loài tảo này là cao nhất trong tự nhiên với tỉ lệ tương đương 7% trọng lượng khô.\r\n\r\n \r\n\r\nTrong nhiều năm liền, các nhà khoa học đã thực hiện các nghiên cứu Invitro và chỉ ra rằng, Astaxanthin “là vua của các hoạt chất oxy hóa” với khả năng chống oxy hóa ưu việt, gấp 100 – 6000 lần các chất chống oxy hóa khác như Vitamin E, Vitamin C và các Beta - carotenoid như lutein, zeaaxanthin .\r\n\r\n ', 'img/Astaxathin2.jpg', 1, 400000),
(11, 'Ostrovit Astaxanthin', NULL, 'img/astaxathin3.jpg', 1, 390000),
(12, 'Triple Strength', NULL, 'img/Astaxathin4.jpg', 1, 450000),
(13, 'True Astaxanthin', NULL, 'img/Astaxathin5.webp', 1, 450000),
(14, 'Organic Astaxanthin', NULL, 'img/Astaxathin6.jpg', 1, 650000),
(15, 'Vistra Astaxathin', NULL, 'img/Astaxathin7.jpg', 1, 410000),
(16, 'Nutricost Astaxathin', NULL, 'img/astaxathin8.jpg', 1, 510000),
(25, 'Đai Lưng', NULL, 'img/Gym11.jpg', 1, 340000),
(26, 'Bao Khuỷu Tay', NULL, 'img/Gym2.jpg', 1, 170000),
(27, 'Bao Tay', NULL, 'img/Gym3.jpg', 1, 75000),
(28, 'Bình Lắc(L)', NULL, 'img/Gym4.jpg', 1, 250000),
(29, 'Bình Lắc(S)', NULL, 'img/Gym5.jpg', 1, 130000),
(30, 'Bao Khớp Gối', NULL, 'img/Gym6.webp', 1, 220000),
(31, 'Bình Nước 2.2L', NULL, 'img/Gym7.jpg', 1, 180000),
(32, 'Bảo Vệ Chân', NULL, 'img/Gym8.jpg', 1, 290000);
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
